name: goub
suffix: ~  # add suffix to saved images
model: denoising
gpu_ids: [0]

sde:
  lambda_square: 30
  T: 100

degradation:
  sigma: 25
  noise_type: G # Gaussian noise: G

datasets:
  test1:
    name: McMaster
    mode: GT
    dataroot_GT: ~

#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    depth: 4

#### path
path:
  pretrain_model_G: ~
